export const personality = [
  'Creative',
  'Adventurous',
  'Calm',
  'Friendly',
  'Confident',
  'Introverted',
  'Extroverted',
  'Optimistic',
  'Curious',
  'Thoughtful',
  'Humorous',
  'Organized',
  'Spontaneous',
  'Open - minded',
  'Responsible',
  'Ambitious',
  'Empathetic',
  'Bold',
  'Patient',
  'Loyal',
  'Passionate',
  'Independent',
  'Generous',
  'Honest',
  'Modest',
  'Practical',
  'Reliable',
  'Perceptive',
  'Determined',
  'Cheerful',
];

export const values = [
  'Integrity',
  'Freedom',
  'Innovation',
  'Family-oriented',
  'Justice',
  'Compassion',
  'Respect',
  'Sustainability',
  'Creativity',
  'Community-focused',
  'Courage',
  'Equality',
  'Gratitude',
  'Hardworking',
  'Honesty',
  'Kindness',
  'Patience',
  'Perseverance',
  'Responsibility',
  'Security',
  'Adventure',
  'Diversity',
  'Ambition',
  'Trustworthiness',
  'Minimalism',
  'Balance',
  'Spirituality',
  'Humor',
  'Optimism',
  'Tradition',
];

export const preferences = [
  'Minimalistic',
  'Vintage',
  'Modern',
  'Sophisticated',
  'Bold',
  'Elegant',
  'Casual',
  'Cultural',
  'Playful',
  'Artistic',
  'Chic',
  'Relaxed',
  'Colorful',
  'Nature-inspired',
  'Neutral',
  'Luxurious',
  'Sporty',
  'Comfortable',
  'Trendy',
  'Classic',
  'Romantic',
  'Retro',
  'Urban',
  'Edgy',
  'Monochromatic',
  'Feminine',
  'Bohemian',
  'Masculine',
  'Quirky',
  'Futuristic',
];

export const PAGE_OPTIONS = {
  personality: {
    list: personality,
    question: 'Who are you at your core?',
    direction: 'Choose up to 5 traits that best describe your personality.',
  },
  values: {
    list: values,
    question: 'What drives you forward?',
    direction: 'Choose up to 5 values that guide your life and decisions.',
  },
  preferences: {
    list: preferences,
    question: 'What do you love most?',
    direction: 'Choose up to 5 styles or tastes that reflect your preferences.',
  },
};
